const skillsData : string[] = [
    "JavaScript",
    "Python",
    "HTML",
    "CSS",
    "React",
    "Node.js",
    "Java",
    "C++",
    "SQL",
    "NoSQL",
    "Flutter",
    "Dart",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "DevOps",
    "Git",
    "REST API",
    "GraphQL",
    "Machine Learning",
    "Data Science",
    "Artificial Intelligence",
    "Cloud Computing",
    "Blockchain",
    "Cybersecurity",
    "Project Management",
    "Agile Methodologies",
    "Scrum",
    "Business Analysis",
    "Sales",
    "Digital Marketing",
    "SEO",
    "Content Marketing",
    "Product Management",
    "Customer Relationship Management (CRM)",
    "Financial Analysis",
    "Business Strategy",
    "Leadership",
    "Entrepreneurship",
    "UI/UX Design",
    "Graphic Design",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Figma",
    "Sketch",
    "Video Editing",
    "3D Modeling",
    "Animation",
    "Communication",
    "Teamwork",
    "Problem Solving",
    "Time Management",
    "Adaptability",
    "Critical Thinking",
    "Creativity",
    "Conflict Resolution",
    "Emotional Intelligence",
    "Negotiation",
    "Public Speaking",
    "Foreign Languages",
    "Writing",
    "Data Entry",
    "Customer Service",
    "Teaching",
    "Research",
    "Other"
  ];
  
  export default skillsData